### ISSUE TITLE
NKX2-5 missing from HuEx database

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nsalomonis/altanalyze#16]
```
This appears to be due to a very long overlapping RNA (UCSC) that is apart of a 
gene neighboring NKX2.5 and spanning it's gene structure. NKX2.5 should be 
included in the database so this should be considered a bug.

```

Original issue reported on code.google.com by `nsalomo...@gmail.com` on 8 May 2012 at 4:28

**Comment by nsalomonis** [comment]
Should be fixed by Ensembl and splicing analysis algorithms that confirm exon-exon junctions align to well-defined isoforms.
