### ISSUE TITLE
Felis Catus Only AltAnalyze Issue

### ISSUE THREAD

**Issue by proteasome** [nsalomonis/altanalyze#36]
When AltAnalyze is installed only with the Fc database and the Human database is not installed, the program crashes after installing the database with the warning:

self.arraycomp.selectitem(self.default_option[0])

Upon restarting AltAnalyze, it crashes again before the application reaches the main menu. This error does not occur with dog, cow or human with EnsMart72. It looks like no default options are being loaded for cat. Occurs with a permission write error for when updating array.txt

**Comment by nsalomonis** [comment]
Should be fixed by adding all supported species codes to appropriate columns in the file: Config/arrays.txt.

**Comment by nsalomonis** [comment]
- [Requires a better long term fix ]

**Comment by proteasome** [comment]
en

***@***.***
CS**mathematics.Python+DATA+DNA+SLA+ASL+#+$+c
Boston University

follow me @en_zyme

________________________________
