### ISSUE TITLE
Error in altanalyze calling getopt.py

### ISSUE THREAD

**Issue by tmari** [nsalomonis/altanalyze#37]
Hi!

I want to use AltAnalyze for my RNA-seq data (specifically to determine transcripts TPMs and splice junctions).
I ran altanalyze as follows:

`altanalyze --platform "RNASeq" --species Hs -fastq_dir /fast/work/users/tmari_m/nbp_project/alt_test/ --groupdir /fast/work/users/tmari_m/nbp_project/alt_test/groups.txt --compdir /fast/work/users/tmari_m/nbp_project/alt_test/comps.txt --output /fast/work/users/tmari_m/nbp_project/alt_test/output --expname test`

but the software immediately stops giving this error message:

`Arguments input: ['AltAnalyze.py', '--platform', 'RNASeq', '--species', 'Hs', '-fastq_dir', '/fast/work/users/tmari_m/nbp_project/alt_test/', '--groupdir', '/fast/work/users/tmari_m/nbp_project/alt_test/groups.txt', '--compdir', '/fast/work/users/tmari_m/nbp_project/alt_test/comps.txt', '--output', '/fast/work/users/tmari_m/nbp_project/alt_test/output', '--expname', 'test']

Traceback (most recent call last):
  File "AltAnalyze.py", line 6347, in commandLineRun
    'downsample=','query=','referenceFull='])
  File "/fast/users/tmari_m/work/miniconda/lib/python2.7/getopt.py", line 90, in getopt
    opts, args = do_shorts(opts, args[0][1:], shortopts, args[1:])
  File "/fast/users/tmari_m/work/miniconda/lib/python2.7/getopt.py", line 190, in do_shorts
    if short_has_arg(opt, shortopts):
  File "/fast/users/tmari_m/work/miniconda/lib/python2.7/getopt.py", line 206, in short_has_arg
    raise GetoptError('option -%s not recognized' % opt, opt)
GetoptError: option -f not recognized

There is an error in the supplied command-line arguments (each flag requires an argument)
`
Do you have any idea what could be the issue? 
Thank you!

**Comment by nsalomonis** [comment]
Greetings,
The command-line options for AltAnalyze require two hyphens and one is missing in the --fastq_dir. Additionally, the option --runKallisto yes should be included, which should allow for the full analysis. For additional details on commands to use, see:
https://github.com/nsalomonis/altanalyze/wiki/CommandLineMode
