### ISSUE TITLE
A custom database

### ISSUE THREAD

**Issue by OlgaVT** [nsalomonis/altanalyze#38]
Good afternoon,
I did not find it in the manual but is it now possible to make an AltAnalyze compatible species database using my own annotation (for example, a custom gtf file)?
Thank you!

**Comment by nsalomonis** [comment]
Great question! Unfortunately, there is currently no gtf to expression database converter. This was a project several years ago, but never completed as the AltAnalyze database ultimately had too many data types to reasonably create the necessary exports. All required files are be imported from the Ensembl SQL database. These include transcript, protein, protein domain and sequence information needed to build the database. Nonetheless, with available information this would be possible but still very challenging.

**Comment by OlgaVT** [comment]
Thank you!
